// js/solar.js
const canvas = document.querySelector('.stars');
canvas.width = window.innerWidth;
canvas.height = window.innerHeight;
const ctx = canvas.getContext('2d');
function drawStars(num) { for(let i=0; i<num; i++) { const x = Math.random()*canvas.width; const y = Math.random()*canvas.height; const r = Math.random()*1.2+0.3; ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI*2); ctx.fillStyle = `rgba(255,255,255,${Math.random()*0.7+0.2})`; ctx.fill(); } }
drawStars(700);
const planets = [ { name: 'النور', color: '#FFD700', size: 110, orbit: 210, angle: 10, page: 'pages/noor.html' }, { name: 'العصا', color: '#C2B280', size: 85, orbit: 280, angle: 48, page: 'pages/asa.html' }, { name: 'النار', color: '#FF5733', size: 97, orbit: 350, angle: 100, page: 'pages/fire.html' }, { name: 'الماء', color: '#3498db', size: 89, orbit: 420, angle: 150, page: 'pages/water.html' }, { name: 'الصوت', color: '#2ecc71', size: 82, orbit: 490, angle: 210, page: 'pages/audio.html' }, { name: 'الفيديو', color: '#9b59b6', size: 94, orbit: 560, angle: 260, page: 'pages/video.html' }, { name: 'المنتدى', color: '#f1c40f', size: 80, orbit: 630, angle: 310, page: 'pages/forum.html' }, { name: 'استشارة', color: '#e67e22', size: 72, orbit: 700, angle: 355, page: 'pages/consult.html' } ];
const system = document.querySelector('.solar-system');
planets.forEach((p, idx) => { const planet = document.createElement('a'); planet.href = p.page; planet.className = 'planet'; planet.style.width = p.size + 'px'; planet.style.height = p.size + 'px'; planet.style.background = `radial-gradient(circle at 35% 35%, ${p.color} 78%, #222 100%)`; planet.style.boxShadow += `, 0 0 30px 14px ${p.color}55`; planet.title = p.name; const label = document.createElement('span'); label.className = 'planet-label'; label.textContent = p.name; planet.appendChild(label); const rad = (p.angle * Math.PI) / 180; const cx = window.innerWidth/2; const cy = window.innerHeight/2; const x = cx + Math.cos(rad) * p.orbit - p.size/2; const y = cy + Math.sin(rad) * p.orbit - p.size/2; planet.style.left = x + 'px'; planet.style.top = y + 'px'; planet.dataset.orbit = p.orbit; planet.dataset.angle = p.angle; planet.dataset.size = p.size; planet.dataset.idx = idx; system.appendChild(planet); });
let tick = 0; function animatePlanets() { tick += 0.35; document.querySelectorAll('.planet').forEach(planet => { const orbit = Number(planet.dataset.orbit); const size = Number(planet.dataset.size); const idx = Number(planet.dataset.idx); const baseAngle = Number(planet.dataset.angle); const angle = baseAngle + tick * (1.08 + idx * 0.14); const rad = (angle * Math.PI) / 180; const cx = window.innerWidth/2; const cy = window.innerHeight/2; planet.style.left = (cx + Math.cos(rad) * orbit - size/2) + 'px'; planet.style.top = (cy + Math.sin(rad) * orbit - size/2) + 'px'; }); requestAnimationFrame(animatePlanets); }
animatePlanets();
window.addEventListener('resize', () => { canvas.width = window.innerWidth; canvas.height = window.innerHeight; ctx.clearRect(0, 0, canvas.width, canvas.height); drawStars(700); });